// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;
using Moq;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawGameStart_977689871e
    {
        private ConsoleVisualizer consoleVisualizer;

        [SetUp]
        public void Setup()
        {
            consoleVisualizer = new ConsoleVisualizer();
        }

        [Test]
        public void DrawGameStart_SingleQuestion_Loaded()
        {
            using (var consoleOutput = new ConsoleOutput())
            {
                consoleVisualizer.DrawGameStart(1);
                Assert.AreEqual("1 question was loaded, press \"enter\" to start the game.\r\n", consoleOutput.GetOuput());
            }
        }

        [Test]
        public void DrawGameStart_MultipleQuestions_Loaded()
        {
            using (var consoleOutput = new ConsoleOutput())
            {
                consoleVisualizer.DrawGameStart(5);
                Assert.AreEqual("5 questions were loaded, press \"enter\" to start the game.\r\n", consoleOutput.GetOuput());
            }
        }

        public class ConsoleOutput : IDisposable
        {
            private StringWriter stringWriter;
            private TextWriter originalOutput;
            
            public ConsoleOutput()
            {
                stringWriter = new StringWriter();
                originalOutput = Console.Out;
                Console.SetOut(stringWriter);
            }
            
            public string GetOuput()
            {
                return stringWriter.ToString();
            }

            public void Dispose()
            {
                Console.SetOut(originalOutput);
                stringWriter.Dispose();
            }
        }
    }
}
