// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;
using System.IO;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawGameStart_977689871e
    {
        private ConsoleVisualizer _consoleVisualizer;
        private StringWriter _stringWriter;

        [SetUp]
        public void SetUp()
        {
            _consoleVisualizer = new ConsoleVisualizer();
            _stringWriter = new StringWriter();
            Console.SetOut(_stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            _stringWriter.Close();
        }

        [Test]
        public void DrawGameStart_SingleQuestion_DisplayCorrectMessage()
        {
            _consoleVisualizer.DrawGameStart(1);
            var output = _stringWriter.GetStringBuilder().ToString().Trim();
            Assert.AreEqual("1 question was loaded, press \"enter\" to start the game.", output);
        }

        [Test]
        public void DrawGameStart_MultipleQuestions_DisplayCorrectMessage()
        {
            _consoleVisualizer.DrawGameStart(3);
            var output = _stringWriter.GetStringBuilder().ToString().Trim();
            Assert.AreEqual("3 questions were loaded, press \"enter\" to start the game.", output);
        }
    }
}
