// Test generated by RoostGPT for test demo5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class is_ChangeHighlightedAnswer_7aa356a4b6
    {
        private Game _quizGame;

        [SetUp]
        public void SetUp()
        {
            _quizGame = new Game();
            _quizGame.CurrentQuestion = new Question 
            {
                Answers = new string[] {"Answer1", "Answer2", "Answer3"}
            };
        }

        [Test]
        public void ChangeHighlightedAnswer_IncrementBeyondAnswerCount_ResetsToZero()
        {
            _quizGame.ChangeHighlightedAnswer(3);
            Assert.AreEqual(0, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_DecrementBelowZero_ResetsToAnswerCountMinusOne()
        {
            _quizGame.ChangeHighlightedAnswer(-1);
            Assert.AreEqual(2, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_IncrementWithinAnswerCount_IncrementsHighlightedAnswerIndex()
        {
            _quizGame.ChangeHighlightedAnswer(1);
            Assert.AreEqual(1, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_DecrementWithinAnswerCount_DecrementsHighlightedAnswerIndex()
        {
            _quizGame.ChangeHighlightedAnswer(1);
            _quizGame.ChangeHighlightedAnswer(-1);
            Assert.AreEqual(0, _quizGame.HighlightedAnswerIndex);
        }
    }
}
