// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using Moq;
using LunarDoggo.QuizGame;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class is_ChangeHighlightedAnswer_7aa356a4b6
    {
        private QuizGame _quizGame;
        private Question _currentQuestion;
        private int _highlightedAnswerIndex;

        [SetUp]
        public void Setup()
        {
            _currentQuestion = new Question { Answers = new string[] { "Answer1", "Answer2", "Answer3" } };
            _quizGame = new QuizGame { CurrentQuestion = _currentQuestion };
            _highlightedAnswerIndex = 0;
        }

        [Test]
        public void ChangeHighlightedAnswer_IncrementPositive_LoopsToStart()
        {
            _quizGame.ChangeHighlightedAnswer(3);
            Assert.AreEqual(0, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_IncrementNegative_LoopsToEnd()
        {
            _quizGame.ChangeHighlightedAnswer(-1);
            Assert.AreEqual(2, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_IncrementWithinRange_ChangesIndex()
        {
            _quizGame.ChangeHighlightedAnswer(1);
            Assert.AreEqual(1, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_IncrementBeyondRange_LoopsToStart()
        {
            _quizGame.ChangeHighlightedAnswer(4);
            Assert.AreEqual(1, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_DecrementWithinRange_ChangesIndex()
        {
            _quizGame.HighlightedAnswerIndex = 2;
            _quizGame.ChangeHighlightedAnswer(-1);
            Assert.AreEqual(1, _quizGame.HighlightedAnswerIndex);
        }

        [Test]
        public void ChangeHighlightedAnswer_DecrementBeyondRange_LoopsToEnd()
        {
            _quizGame.ChangeHighlightedAnswer(-4);
            Assert.AreEqual(2, _quizGame.HighlightedAnswerIndex);
        }
    }
}
