// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using LunarDoggo.FileSystemTree.Tests;

namespace LunarDoggo.FileSystemTree.Tests
{
    [TestFixture]
    public class FileSystemTreeTests
    {
        [Test]
        public void TestGetBaseDirectoryPath_ValidDirectoryPath_InputExists_ReturnsPath()
        {
            // Arrange
            string directoryPath = "C:\\Users\\";
            string expectedPath = directoryPath;

            // Act
            string actualPath = FileSystemTree.GetBaseDirectoryPath(directoryPath);

            // Assert
            Assert.AreEqual(expectedPath, actualPath);
        }

        [Test]
        public void TestGetBaseDirectoryPath_ValidDirectoryPath_InputDoesNotExist_PromptsUntilValidDirectoryPathEntered()
        {
            // Arrange
            string directoryPath = "C:\\InvalidDirectory\\";
            string expectedPath = "C:\\Users\\";

            // Mock user input
            Console.SetIn(new StringReader($"{expectedPath}{Environment.NewLine}"));

            // Act
            string actualPath = FileSystemTree.GetBaseDirectoryPath(directoryPath);

            // Assert
            Assert.AreEqual(expectedPath, actualPath);
        }
    }
}
