// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System;
using System.IO;
using NUnit.Framework;
using LunarDoggo.FileSystemTree.Tests;

namespace LunarDoggo.FileSystemTree.Tests
{
    [TestFixture]
    public class ProgramTests
    {
        [Test]
        public void TestGetBaseDirectoryPath_ValidPath()
        {
            // Arrange
            var expectedPath = "C:\\Users\\Test";

            // Act
            using (StringReader sr = new StringReader(expectedPath))
            {
                Console.SetIn(sr);

                string result = Program.GetBaseDirectoryPath();

                // Assert
                Assert.AreEqual(expectedPath, result);
            }
        }

        [Test]
        public void TestGetBaseDirectoryPath_InvalidPath()
        {
            // Arrange
            var expectedPath = "C:\\SomeNonexistentDirectory";

            // Act
            using (StringReader sr = new StringReader(expectedPath))
            {
                Console.SetIn(sr);

                string result = Program.GetBaseDirectoryPath();

                // Assert
                Assert.AreEqual(expectedPath, result);
            }
        }
    }
}
