// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;
using System.IO;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawGameResult_127a94cb29
    {
        private ConsoleVisualizer visualizer;
        private StringWriter stringWriter;
        private StringReader stringReader;

        [SetUp]
        public void Setup()
        {
            this.visualizer = new ConsoleVisualizer();
            this.stringWriter = new StringWriter();
            Console.SetOut(this.stringWriter);
            this.stringReader = new StringReader(string.Empty);
            Console.SetIn(this.stringReader);
        }

        [TearDown]
        public void TearDown()
        {
            this.stringWriter.Close();
            this.stringReader.Close();
        }

        [Test]
        public void DrawGameResult_AllQuestionsCorrect()
        {
            this.visualizer.DrawGameResult(10, 10);
            Assert.That(this.stringWriter.ToString(), Does.Contain("You got 10 out of 10 question right. Continue with \"enter\"."));
        }

        [Test]
        public void DrawGameResult_NoQuestionsCorrect()
        {
            this.visualizer.DrawGameResult(10, 0);
            Assert.That(this.stringWriter.ToString(), Does.Contain("You got 0 out of 10 question right. Continue with \"enter\"."));
        }

        [Test]
        public void DrawGameResult_SomeQuestionsCorrect()
        {
            this.visualizer.DrawGameResult(10, 5);
            Assert.That(this.stringWriter.ToString(), Does.Contain("You got 5 out of 10 question right. Continue with \"enter\"."));
        }
    }
}
