// Test generated by RoostGPT for test efghi using AI Type Open AI and AI Model gpt-4

using System;
using System.Collections.Generic;
using NUnit.Framework;
using LunarDoggo.FileSystemTree;

namespace LunarDoggo.FileSystemTree.Tests
{
    [TestFixture]
    public class FileSystemTreeItemTests
    {
        [Test]
        public void TestFileSystemTreeItem_FileSystemTreeItem_a6b8e2882a()
        {
            // Arrange
            string expectedName = "Test";
            FileSystemTreeItemType expectedType = FileSystemTreeItemType.File;
            List<FileSystemTreeItem> expectedChildren = new List<FileSystemTreeItem>
            {
                new FileSystemTreeItem("Child1", FileSystemTreeItemType.File, null),
                new FileSystemTreeItem("Child2", FileSystemTreeItemType.Folder, null)
            };

            // Act
            FileSystemTreeItem item = new FileSystemTreeItem(expectedName, expectedType, expectedChildren);

            // Assert
            Assert.AreEqual(expectedName, item.name);
            Assert.AreEqual(expectedType, item.type);
            Assert.AreEqual(expectedChildren, item.children);
        }

        [Test]
        public void TestFileSystemTreeItem_FileSystemTreeItem_NullChildren_a6b8e2882a()
        {
            // Arrange
            string expectedName = "Test";
            FileSystemTreeItemType expectedType = FileSystemTreeItemType.File;
            IEnumerable<FileSystemTreeItem> expectedChildren = null;

            // Act
            FileSystemTreeItem item = new FileSystemTreeItem(expectedName, expectedType, expectedChildren);

            // Assert
            Assert.AreEqual(expectedName, item.name);
            Assert.AreEqual(expectedType, item.type);
            Assert.IsNull(item.children);
        }
    }
}
