// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System.Collections.Generic;

namespace LunarDoggo.QuizGame
{
    public class QuizQuestion
    {
        public Guid Id { get; set; }
        public string Text { get; set; }
        public List<QuizQuestionAnswer> Answers { get; set; }
    }

    public class QuizQuestionAnswer
    {
        public Guid Id { get; set; }
        public string Text { get; set; }
        public bool IsCorrect { get; set; }
    }
}
