// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using LunarDoggo.QuizGame.IO;
using System.Collections.Generic;
using System.Text.Json;
using System.IO;
using System;

namespace LunarDoggo.QuizGame.IO.Test
{
    [TestFixture]
    public class DeserializeQuestions_e19f50e5a6
    {
        private FileQuizQuestionSerializer _fileQuizQuestionSerializer;
        private string _filePath;

        [SetUp]
        public void SetUp()
        {
            _filePath = "test.json"; // TODO: Change this to the path of your test file
            _fileQuizQuestionSerializer = new FileQuizQuestionSerializer(_filePath);
        }

        [Test]
        public void DeserializeQuestions_FileExists_ReturnsQuestions()
        {
            var questions = _fileQuizQuestionSerializer.DeserializeQuestions();

            Assert.IsNotNull(questions);
            Assert.IsNotEmpty(questions);
            foreach (var question in questions)
            {
                Assert.AreNotEqual(Guid.Empty, question.Id);
                Assert.IsNotNull(question.Answers);
                Assert.IsNotEmpty(question.Answers);
                foreach (var answer in question.Answers)
                {
                    Assert.AreNotEqual(Guid.Empty, answer.Id);
                }
            }
        }

        [Test]
        public void DeserializeQuestions_FileDoesNotExist_ReturnsEmpty()
        {
            _filePath = "nonexistent.json"; // TODO: Change this to a non-existent file path
            _fileQuizQuestionSerializer = new FileQuizQuestionSerializer(_filePath);

            var questions = _fileQuizQuestionSerializer.DeserializeQuestions();

            Assert.IsNotNull(questions);
            Assert.IsEmpty(questions);
        }
    }
}
