// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using LunarDoggo.QuizGame.IO;
using NUnit.Framework;

namespace LunarDoggo.QuizGame.IO.Test
{
    [TestFixture]
    public class DeserializeQuestions_e19f50e5a6
    {
        private string _filePath;
        private FileQuizQuestionSerializer _serializer;

        [SetUp]
        public void Setup()
        {
            _filePath = "test.json"; // TODO: Change this to your test file path
            _serializer = new FileQuizQuestionSerializer(_filePath);
        }

        [Test]
        public void DeserializeQuestions_WhenFileExists_ReturnsNotEmpty()
        {
            // Act
            var result = _serializer.DeserializeQuestions();

            // Assert
            Assert.IsNotNull(result);
            Assert.IsNotEmpty(result);
        }

        [Test]
        public void DeserializeQuestions_WhenFileNotExists_ReturnsEmpty()
        {
            // Arrange
            _serializer = new FileQuizQuestionSerializer("nonexistent.json");

            // Act
            var result = _serializer.DeserializeQuestions();

            // Assert
            Assert.IsNotNull(result);
            Assert.IsEmpty(result);
        }

        [Test]
        public void DeserializeQuestions_WhenFileContainsInvalidJson_ThrowsException()
        {
            // Arrange
            File.WriteAllText(_filePath, "{ invalid json }");
            
            // Act & Assert
            Assert.Throws<JsonException>(() => _serializer.DeserializeQuestions());
        }

        [TearDown]
        public void TearDown()
        {
            if (File.Exists(_filePath))
            {
                File.Delete(_filePath);
            }
        }
    }
}
