// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.Collections.Generic;
using NUnit.Framework;
using LunarDoggo.FileSystemTree;
using LunarDoggo.FileSystemTree.Test;

namespace LunarDoggo.FileSystemTree.Test
{
    [TestFixture]
    public class FileSystemTreeItem_2e95657d4a
    {
        private FileSystemTreeItem fileSystemTreeItem;

        [SetUp]
        public void Setup()
        {
            IEnumerable<FileSystemTreeItem> children = new List<FileSystemTreeItem>
            {
                new FileSystemTreeItem("Child1", FileSystemTreeItemType.File, null),
                new FileSystemTreeItem("Child2", FileSystemTreeItemType.Directory, null)
            };

            fileSystemTreeItem = new FileSystemTreeItem("Parent", FileSystemTreeItemType.Directory, children);
        }

        [Test]
        public void TestFileSystemTreeItemCreation()
        {
            Assert.IsNotNull(fileSystemTreeItem);
            Assert.AreEqual("Parent", fileSystemTreeItem.Name);
            Assert.AreEqual(FileSystemTreeItemType.Directory, fileSystemTreeItem.Type);
            Assert.IsNotNull(fileSystemTreeItem.Children);
            Assert.AreEqual(2, fileSystemTreeItem.Children.Count);
        }

        [Test]
        public void TestFileSystemTreeItemCreationWithNoChildren()
        {
            FileSystemTreeItem item = new FileSystemTreeItem("NoChildren", FileSystemTreeItemType.File, null);
            
            Assert.IsNotNull(item);
            Assert.AreEqual("NoChildren", item.Name);
            Assert.AreEqual(FileSystemTreeItemType.File, item.Type);
            Assert.IsNull(item.Children);
        }
    }
}
