// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.Collections.Generic;
using NUnit.Framework;
using LunarDoggo.FileSystemTree;
using LunarDoggo.FileSystemTree.Test;

namespace LunarDoggo.FileSystemTree.Test
{
    [TestFixture]
    public class FileSystemTreeItem_2e95657d4a
    {
        private FileSystemTreeItem fileSystemTreeItem;

        [SetUp]
        public void Setup()
        {
            IEnumerable<FileSystemTreeItem> children = new List<FileSystemTreeItem>
            {
                new FileSystemTreeItem("Child1", FileSystemTreeItemType.File, null),
                new FileSystemTreeItem("Child2", FileSystemTreeItemType.Directory, null)
            };

            fileSystemTreeItem = new FileSystemTreeItem("Parent", FileSystemTreeItemType.Directory, children);
        }

        [Test]
        public void TestFileSystemTreeItemCreation()
        {
            Assert.AreEqual("Parent", fileSystemTreeItem.name);
            Assert.AreEqual(FileSystemTreeItemType.Directory, fileSystemTreeItem.type);
            Assert.AreEqual(2, fileSystemTreeItem.children.Count);
        }

        [Test]
        public void TestFileSystemTreeItemCreationNullChildren()
        {
            FileSystemTreeItem fileSystemTreeItemWithNullChildren = new FileSystemTreeItem("Parent", FileSystemTreeItemType.Directory, null);
            Assert.AreEqual("Parent", fileSystemTreeItemWithNullChildren.name);
            Assert.AreEqual(FileSystemTreeItemType.Directory, fileSystemTreeItemWithNullChildren.type);
            Assert.IsNull(fileSystemTreeItemWithNullChildren.children);
        }
    }
}
