// Test generated by RoostGPT for test demo5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using LunarDoggo.QuizGame;
using System;

namespace LunarDoggo.QuizGame.Test
{
    public class contains_ProcessEnterPress_715cac28e5
    {
        private Game game;

        [SetUp]
        public void Setup()
        {
            this.game = new Game();
        }

        [Test]
        public void Test_ProcessEnterPress_NotStarted()
        {
            Assert.IsFalse(this.game.IsStarted);
            this.game.ProcessEnterPress();
            Assert.IsTrue(this.game.IsStarted);
        }

        [Test]
        public void Test_ProcessEnterPress_StartedButNotAnswered()
        {
            this.game.Start();
            Assert.IsTrue(this.game.IsStarted);
            Assert.IsFalse(this.game.State.IsCurrentQuestionAnswered);
            this.game.ProcessEnterPress();
            Assert.IsTrue(this.game.State.IsCurrentQuestionAnswered);
        }

        [Test]
        public void Test_ProcessEnterPress_StartedAndAnswered()
        {
            this.game.Start();
            this.game.State.AnswerQuestion();
            Assert.IsTrue(this.game.State.IsCurrentQuestionAnswered);
            this.game.ProcessEnterPress();
            Assert.IsFalse(this.game.State.IsCurrentQuestionAnswered);
        }

        [Test]
        public void Test_ProcessEnterPress_StartedAndAnswered_MoveToNextQuestion()
        {
            this.game.Start();
            this.game.State.AnswerQuestion();
            var currentQuestion = this.game.State.CurrentQuestion;
            this.game.ProcessEnterPress();
            Assert.AreNotEqual(currentQuestion, this.game.State.CurrentQuestion);
        }
    }
}
