// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

[TestFixture]
public class ProcessEnterPressTest
{
    private State state;
    private bool isStarted;
    
    [SetUp]
    public void SetUp()
    {
        state = new State();
        isStarted = false;
    }
    
    [Test]
    public void GivenStartedStateAndCurrentQuestionAnswered_WhenProcessEnterPress_ThenMoveToNextQuestion()
    {
        // Arrange
        isStarted = true;
        state.IsCurrentQuestionAnswered = true;
        
        // Act
        ProcessEnterPress();
        
        // Assert
        Assert.That(state.CurrentQuestionIndex, Is.EqualTo(1));
    }
    
    [Test]
    public void GivenStartedStateAndCurrentQuestionNotAnswered_WhenProcessEnterPress_ThenAnswerQuestion()
    {
        // Arrange
        isStarted = true;
        state.IsCurrentQuestionAnswered = false;
        
        // Act
        ProcessEnterPress();
        
        // Assert
        Assert.That(state.CurrentQuestionIndex, Is.EqualTo(0));
    }
    
    [Test]
    public void GivenNotStartedState_WhenProcessEnterPress_ThenMoveToNextQuestion()
    {
        // Arrange
        isStarted = false;
        
        // Act
        ProcessEnterPress();
        
        // Assert
        Assert.That(state.CurrentQuestionIndex, Is.EqualTo(1));
    }
}
