// Test generated by RoostGPT for test demo5 using AI Type Open AI and AI Model gpt-4

using System;
using System.IO;
using NUnit.Framework;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_DrawPlayAgain_2e6317dc73
    {
        private StringWriter stringWriter;
        private TextWriter originalOutput;

        [SetUp]
        public void SetUp()
        {
            this.stringWriter = new StringWriter();
            this.originalOutput = Console.Out;
            Console.SetOut(this.stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            Console.SetOut(this.originalOutput);
            this.stringWriter.Dispose();
        }

        [Test]
        public void DrawPlayAgain_WritesExpectedMessageToConsole()
        {
            // Arrange
            var expectedMessage = "Do you like to play again? (Y/N)" + Environment.NewLine;

            // Act
            DrawPlayAgain();

            // Assert
            Assert.AreEqual(expectedMessage, this.stringWriter.ToString());
        }

        [Test]
        public void DrawPlayAgain_DoesNotWriteUnexpectedMessageToConsole()
        {
            // Arrange
            var unexpectedMessage = "Unexpected Message";

            // Act
            DrawPlayAgain();

            // Assert
            Assert.AreNotEqual(unexpectedMessage, this.stringWriter.ToString());
        }

        public void DrawPlayAgain()
        {
            Console.WriteLine("Do you like to play again? (Y/N)");
        }
    }
}
