// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using System;

namespace TestProject
{
    [TestFixture]
    public class ConsoleVisualizer_DrawPlayAgain_2e6317dc73
    {
        [Test]
        public void DrawPlayAgain_Should_Print_YN_Message()
        {
            // Arrange
            var consoleOutput = new System.IO.StringWriter();
            Console.SetOut(consoleOutput);

            // Act
            DrawPlayAgain();

            // Assert
            Assert.AreEqual("Do you like to play again? (Y/N)\r\n", consoleOutput.ToString());
        }
        
        [Test]
        public void DrawPlayAgain_Should_Not_Throw_Exception()
        {
            // Arrange
            var consoleOutput = new System.IO.StringWriter();
            Console.SetOut(consoleOutput);

            // Act and Assert
            Assert.DoesNotThrow(() => DrawPlayAgain());
        }

        private void DrawPlayAgain()
        {
            Console.WriteLine("Do you like to play again? (Y/N)");
        }
    }
}
