// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using System;
using System.IO;
using NUnit.Framework;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_DrawPlayAgain_2e6317dc73
    {
        private StringWriter stringWriter;
        private ConsoleVisualizer consoleVisualizer;

        [SetUp]
        public void SetUp()
        {
            stringWriter = new StringWriter();
            Console.SetOut(stringWriter);
            consoleVisualizer = new ConsoleVisualizer();
        }

        [Test]
        public void DrawPlayAgain_PrintsCorrectMessage()
        {
            consoleVisualizer.DrawPlayAgain();

            string expectedOutput = "Do you like to play again? (Y/N)" + Environment.NewLine;
            Assert.AreEqual(expectedOutput, stringWriter.ToString());
        }

        [Test]
        public void DrawPlayAgain_PrintsOnlyOneMessage()
        {
            consoleVisualizer.DrawPlayAgain();

            int lineCount = stringWriter.ToString().Split(Environment.NewLine).Length - 1;
            Assert.AreEqual(1, lineCount);
        }

        [TearDown]
        public void TearDown()
        {
            stringWriter.Close();
        }
    }
}
