// Test generated by RoostGPT for test demo5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class HighlightPreviousAnswerTest
    {
        private LunarDoggo.QuizGame.Game _quizGame;

        [SetUp]
        public void Setup()
        {
            _quizGame = new LunarDoggo.QuizGame.Game();
        }

        [Test]
        public void Test_HighlightPreviousAnswer_WhenThereIsPreviousAnswer()
        {
            // TODO: Set initial state where there is a previous answer

            _quizGame.HighlightPreviousAnswer();

            // TODO: Verify that the previous answer is highlighted
        }

        [Test]
        public void Test_HighlightPreviousAnswer_WhenThereIsNoPreviousAnswer()
        {
            // TODO: Set initial state where there is no previous answer

            _quizGame.HighlightPreviousAnswer();

            // TODO: Verify that no answer is highlighted
        }

        [TearDown]
        public void TearDown()
        {
            _quizGame = null;
        }
    }
}
