// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Collections.Immutable;
using NUnit.Framework;
using Moq;
using LunarDoggo.FileSystemTree.Test;

namespace LunarDoggo.FileSystemTree.Test
{
    [TestFixture]
    public class OutputFileSystemTreeLevel_1127e4e443
    {
        private StringWriter stringWriter;

        [SetUp]
        public void SetUp()
        {
            stringWriter = new StringWriter();
            Console.SetOut(stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            stringWriter.Dispose();
        }

        [Test]
        public void Test_OutputFileSystemTreeLevel_WithNoChildren()
        {
            FileSystemTreeItem item = new FileSystemTreeItem()
            {
                Name = "Test",
                Type = "Folder",
                Children = new List<FileSystemTreeItem>()
            };

            Program.OutputFileSystemTreeLevel(1, item);

            string expected = "  Test (Folder)\r\n";
            Assert.AreEqual(expected, stringWriter.ToString());
        }

        [Test]
        public void Test_OutputFileSystemTreeLevel_WithChildren()
        {
            FileSystemTreeItem childItem = new FileSystemTreeItem()
            {
                Name = "ChildTest",
                Type = "Folder",
                Children = new List<FileSystemTreeItem>()
            };

            FileSystemTreeItem parentItem = new FileSystemTreeItem()
            {
                Name = "ParentTest",
                Type = "Folder",
                Children = new List<FileSystemTreeItem> { childItem }
            };

            Program.OutputFileSystemTreeLevel(1, parentItem);

            string expected = "  ParentTest (Folder)\r\n    ChildTest (Folder)\r\n";
            Assert.AreEqual(expected, stringWriter.ToString());
        }
    }
}
