// Test generated by RoostGPT for test demo56 using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;
using TicTacToe;

namespace TicTacToe.Tests
{
    [TestFixture]
    public class MainWindowTests
    {
        private MainWindow _mainWindow;
        private ButtonTileMapping _buttonTileMapping1, _buttonTileMapping2;

        [SetUp]
        public void Setup()
        {
            _mainWindow = new MainWindow();
            _buttonTileMapping1 = new ButtonTileMapping { Button = new System.Windows.Controls.Button { Content = "X" } };
            _buttonTileMapping2 = new ButtonTileMapping { Button = new System.Windows.Controls.Button { Content = "O" } };
            _mainWindow.buttonTileMappings = new System.Collections.Generic.List<ButtonTileMapping> { _buttonTileMapping1, _buttonTileMapping2 };
        }

        [Test]
        public void TestMainWindow_OnTilesReset_86ec45c76e()
        {
            // Act
            _mainWindow.OnTilesReset(this, EventArgs.Empty);

            // Assert
            Assert.AreEqual("", _buttonTileMapping1.Button.Content);
            Assert.AreEqual("", _buttonTileMapping2.Button.Content);
        }
    }
}
