// Test generated by RoostGPT for test demo56 using AI Type Open AI and AI Model gpt-4
using System;
using System.Linq;
using NUnit.Framework;
using LunarDoggo.TicTacToe;
using System.Windows.Controls;

namespace TicTacToeTests
{
    [TestFixture]
    public class MainWindowTests
    {
        private MainWindow _window;

        [SetUp]
        public void Setup()
        {
            _window = new MainWindow();
        }

        [Test]
        public void TestMainWindow_GetButtonTileMappings_855bdcb083()
        {
            var result = _window.GetButtonTileMappings();

            Assert.AreEqual(9, result.Length);

            AssertButtonTileMapping(result[0], _window.btnTopLeft, 0, 0);
            AssertButtonTileMapping(result[1], _window.btnTopCenter, 1, 0);
            AssertButtonTileMapping(result[2], _window.btnTopRight, 2, 0);
            AssertButtonTileMapping(result[3], _window.btnMiddleLeft, 0, 1);
            AssertButtonTileMapping(result[4], _window.btnMiddleCenter, 1, 1);
            AssertButtonTileMapping(result[5], _window.btnMiddleRight, 2, 1);
            AssertButtonTileMapping(result[6], _window.btnBottomLeft, 0, 2);
            AssertButtonTileMapping(result[7], _window.btnBottomCenter, 1, 2);
            AssertButtonTileMapping(result[8], _window.btnBottomRight, 2, 2);
        }

        private void AssertButtonTileMapping(ButtonTileMapping mapping, Button expectedButton, int expectedX, int expectedY)
        {
            Assert.AreEqual(expectedButton, mapping.Button);
            Assert.AreEqual(expectedX, mapping.X);
            Assert.AreEqual(expectedY, mapping.Y);
        }
    }
}
