// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using LunarDoggo.QuizGame.IO;
using System.IO;

namespace LunarDoggo.QuizGame.IO.Test
{
    [TestFixture]
    public class FileQuizQuestionSerializer_FileQuizQuestionSerializer_8ce3b37241
    {
        private string filePath;

        [SetUp]
        public void Setup()
        {
            // TODO: Replace with the actual file path
            this.filePath = "testFilePath.txt";
        }

        [Test]
        public void FileQuizQuestionSerializer_ValidFilePath_Success()
        {
            // Arrange
            var serializer = new FileQuizQuestionSerializer(this.filePath);

            // Act & Assert
            Assert.IsNotNull(serializer);
        }

        [Test]
        public void FileQuizQuestionSerializer_EmptyFilePath_ThrowsArgumentException()
        {
            // Arrange
            string emptyFilePath = string.Empty;

            // Act & Assert
            Assert.Throws<ArgumentException>(() => new FileQuizQuestionSerializer(emptyFilePath));
        }

        [Test]
        public void FileQuizQuestionSerializer_NullFilePath_ThrowsArgumentNullException()
        {
            // Arrange
            string nullFilePath = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new FileQuizQuestionSerializer(nullFilePath));
        }

        [Test]
        public void FileQuizQuestionSerializer_NonExistentFilePath_ThrowsFileNotFoundException()
        {
            // Arrange
            string nonExistentFilePath = "nonExistentFilePath.txt";

            // Act & Assert
            Assert.Throws<FileNotFoundException>(() => new FileQuizQuestionSerializer(nonExistentFilePath));
        }
    }
}
