// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.IO;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using Moq;

namespace LunarDoggo.FileSystemTree.Test
{
    [TestFixture]
    public class GetBaseDirectoryPath_3a1a151596
    {
        private Mock<TextReader> consoleInputMock;

        [SetUp]
        public void SetUp()
        {
            consoleInputMock = new Mock<TextReader>();
            Console.SetIn(consoleInputMock.Object);
        }

        [Test]
        public void GetBaseDirectoryPath_ReturnsValidDirectoryPath_WhenValidPathIsEntered()
        {
            // Arrange
            string expectedPath = AppDomain.CurrentDomain.BaseDirectory;
            consoleInputMock.SetupSequence(m => m.ReadLine())
                .Returns("invalid path")
                .Returns(expectedPath);

            // Act
            string actualPath = Program.GetBaseDirectoryPath();

            // Assert
            Assert.AreEqual(expectedPath, actualPath);
        }

        [Test]
        public void GetBaseDirectoryPath_ThrowsException_WhenNullIsEntered()
        {
            // Arrange
            consoleInputMock.Setup(m => m.ReadLine()).Returns((string)null);

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => Program.GetBaseDirectoryPath());
        }
    }
}
