// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using NUnit.Framework;
using LunarDoggo.FileSystemTree;

namespace LunarDoggo.FileSystemTree.Tests
{
    public class FileSystemTreeTests
    {
        [Test]
        public void TestProgram_OutputFileSystemTreeLevel_9fe43fbdc7()
        {
            var program = new Program();
            var stringWriter = new StringWriter();
            Console.SetOut(stringWriter);

            var item = new FileSystemTreeItem
            {
                Name = "Root",
                Type = "Folder",
                Children = new List<FileSystemTreeItem>
                {
                    new FileSystemTreeItem
                    {
                        Name = "Child1",
                        Type = "File"
                    },
                    new FileSystemTreeItem
                    {
                        Name = "Child2",
                        Type = "Folder",
                        Children = new List<FileSystemTreeItem>
                        {
                            new FileSystemTreeItem
                            {
                                Name = "Grandchild1",
                                Type = "File"
                            }
                        }
                    }
                }
            };

            program.OutputFileSystemTreeLevel(0, item);

            var expectedOutput = "Root (Folder)\n  Child1 (File)\n  Child2 (Folder)\n    Grandchild1 (File)\n";
            Assert.AreEqual(expectedOutput, stringWriter.ToString());
        }

        [Test]
        public void TestProgram_OutputFileSystemTreeLevel_NullItem_9fe43fbdc7()
        {
            var program = new Program();
            var stringWriter = new StringWriter();
            Console.SetOut(stringWriter);

            program.OutputFileSystemTreeLevel(0, null);

            var expectedOutput = "";
            Assert.AreEqual(expectedOutput, stringWriter.ToString());
        }
    }
}
