// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;
using LunarDoggo.TicTacToe;

namespace LunarDoggo.TicTacToe.Tests
{
    [TestFixture]
    public class GameBoardTests
    {
        private GameBoard _gameBoard;

        [SetUp]
        public void SetUp()
        {
            _gameBoard = new GameBoard();
        }

        [Test]
        public void TestGameBoard_IsTileOccupied_432dfacbd8()
        {
            // TODO: Initialize the game board with some tiles occupied

            Assert.IsTrue(_gameBoard.IsTileOccupied(1, 1), "Tile (1,1) should be occupied");

            Assert.IsFalse(_gameBoard.IsTileOccupied(0, 0), "Tile (0,0) should not be occupied");
        }

        [Test]
        public void TestGameBoard_IsTileOccupied_OutOfBounds()
        {
            // TODO: Initialize the game board with some tiles occupied

            Assert.Throws<IndexOutOfRangeException>(() => _gameBoard.IsTileOccupied(-1, 0), "Checking tile (-1,0) should throw IndexOutOfRangeException");

            Assert.Throws<IndexOutOfRangeException>(() => _gameBoard.IsTileOccupied(0, -1), "Checking tile (0,-1) should throw IndexOutOfRangeException");

            Assert.Throws<IndexOutOfRangeException>(() => _gameBoard.IsTileOccupied(3, 0), "Checking tile (3,0) should throw IndexOutOfRangeException");

            Assert.Throws<IndexOutOfRangeException>(() => _gameBoard.IsTileOccupied(0, 3), "Checking tile (0,3) should throw IndexOutOfRangeException");
        }
    }
}
