// Test generated by RoostGPT for test demo5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using Moq;
using System.Collections.Generic;

[TestFixture]
public class Program_RunGameLoop_25b3411b88
{
    private Mock<IQuizVisualizer> _visualizerMock;
    private IEnumerable<QuizQuestion> _questions;

    [SetUp]
    public void Setup()
    {
        _visualizerMock = new Mock<IQuizVisualizer>();
        _questions = new List<QuizQuestion>
        {
            new QuizQuestion("Question 1", "Answer 1"),
            new QuizQuestion("Question 2", "Answer 2"),
            new QuizQuestion("Question 3", "Answer 3")
        };
    }

    [Test]
    public void RunGameLoop_GameLoopIsFinished_VisualizerDrawPlayAgainIsCalled()
    {
        // Arrange
        var gameLoop = new GameLoop(_visualizerMock.Object, _questions);

        // Act
        while (!gameLoop.IsFinished)
        {
            gameLoop.DoTick();
        }

        // Assert
        _visualizerMock.Verify(v => v.DrawPlayAgain(), Times.Once);
    }

    [Test]
    public void RunGameLoop_GameLoopIsNotFinished_VisualizerDrawPlayAgainIsNotCalled()
    {
        // Arrange
        var gameLoop = new GameLoop(_visualizerMock.Object, _questions);

        // Act
        // Simulate game loop not finished
        if (gameLoop.IsFinished)
        {
            gameLoop.DoTick();
        }

        // Assert
        _visualizerMock.Verify(v => v.DrawPlayAgain(), Times.Never);
    }
}
