// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using System.Collections.Generic;

[TestFixture]
public class Program_RunGameLoop_25b3411b88
{
    [Test]
    public void RunGameLoop_WhenQuestionsIsEmpty_ShouldNotEnterGameLoop()
    {
        // Arrange
        IEnumerable<QuizQuestion> emptyQuestions = new List<QuizQuestion>();

        // Act
        Program.RunGameLoop(emptyQuestions);

        // Assert
        // TODO: Verify that gameLoop.DoTick() is never called
        // TODO: Verify that Program.Visualizer.DrawPlayAgain() is called once
    }

    [Test]
    public void RunGameLoop_WhenQuestionsHasMultipleQuestions_ShouldEnterGameLoopUntilFinished()
    {
        // Arrange
        IEnumerable<QuizQuestion> multipleQuestions = new List<QuizQuestion>
        {
            new QuizQuestion(),
            new QuizQuestion(),
            new QuizQuestion()
        };

        // Act
        Program.RunGameLoop(multipleQuestions);

        // Assert
        // TODO: Verify that gameLoop.DoTick() is called multiple times until gameLoop.IsFinished is true
        // TODO: Verify that Program.Visualizer.DrawPlayAgain() is called once
    }
}
