// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Collections.Immutable;
using NUnit.Framework;
using LunarDoggo.FileSystemTree;

namespace LunarDoggo.FileSystemTree.Tests
{
    [TestFixture]
    public class ProgramTests
    {
        [Test]
        public void TestProgram_Main_e1a933a43f()
        {
            // Arrange
            string expectedBaseDirectoryPath = AppDomain.CurrentDomain.BaseDirectory;
            DirectoryInfo expectedBaseDirectory = new DirectoryInfo(expectedBaseDirectoryPath);
            FileSystemTreeItem expectedFileSystemTree = Program.GetFileSystemTree(expectedBaseDirectory);

            StringWriter stringWriter = new StringWriter();
            Console.SetOut(stringWriter);

            // Act
            Program.Main(new string[] { });

            // Assert
            string actualOutput = stringWriter.ToString();
            string expectedOutput = expectedFileSystemTree.ToString();
            Assert.AreEqual(expectedOutput, actualOutput);
        }

        [Test]
        public void TestProgram_Main_InvalidBaseDirectory()
        {
            // Arrange
            string invalidDirectoryPath = "Z:\\InvalidDirectoryPath";
            Program.GetBaseDirectoryPath = () => invalidDirectoryPath;

            // Act & Assert
            var ex = Assert.Throws<DirectoryNotFoundException>(() => Program.Main(new string[] { }));
            Assert.That(ex.Message, Is.EqualTo($"Could not find a part of the path '{invalidDirectoryPath}'."));
        }
    }
}
