// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Collections.Immutable;
using LunarDoggo.FileSystemTree;

namespace LunarDoggo.FileSystemTree.Tests
{
    [TestFixture]
    public class ProgramTests
    {
        [Test]
        public void TestProgram_Main_e1a933a43f()
        {
            string baseDirectoryPath = Program.GetBaseDirectoryPath();
            DirectoryInfo baseDirectory = new DirectoryInfo(baseDirectoryPath);

            FileSystemTreeItem fileSystemTree = Program.GetFileSystemTree(baseDirectory);

            Program.OutputFileSystemTreeLevel(0, fileSystemTree);

            // TODO: Replace with actual expected output
            string expectedOutput = "";

            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw);
                Program.Main(new string[] { });

                string result = sw.ToString().Trim();

                Assert.AreEqual(expectedOutput, result);
            }
        }

        [Test]
        public void TestProgram_Main_InvalidDirectory()
        {
            // TODO: Replace with an invalid directory path
            string invalidDirectoryPath = "";

            Assert.Throws<DirectoryNotFoundException>(() => Program.Main(new string[] { invalidDirectoryPath }));
        }
    }
}
