// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Collections.Immutable;
using NUnit.Framework;
using Moq;

namespace LunarDoggo.FileSystemTree
{
    [TestFixture]
    public class TestProgram_GetBaseDirectoryPath_7667d18cd1
    {
        private Mock<ConsoleWrapper> consoleMock;

        [SetUp]
        public void SetUp()
        {
            this.consoleMock = new Mock<ConsoleWrapper>();
        }

        [Test]
        public void TestValidDirectoryPath()
        {
            //Arrange
            var validPath = Directory.GetCurrentDirectory(); 
            consoleMock.SetupSequence(m => m.ReadLine()).Returns(validPath);

            //Act
            var result = Program.GetBaseDirectoryPath(consoleMock.Object);

            //Assert
            Assert.AreEqual(validPath, result);
        }

        [Test]
        public void TestInvalidDirectoryPath()
        {
            //Arrange
            var invalidPath = "InvalidPath";
            var validPath = Directory.GetCurrentDirectory();
            consoleMock.SetupSequence(m => m.ReadLine()).Returns(invalidPath).Returns(validPath);

            //Act
            var result = Program.GetBaseDirectoryPath(consoleMock.Object);

            //Assert
            Assert.AreEqual(validPath, result);
        }
    }
    
    public class ConsoleWrapper
    {
        public virtual string ReadLine()
        {
            return Console.ReadLine();
        }
    }
}
