// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using System;
using System.IO;
using System.Collections.Generic;
using LunarDoggo.QuizGame.IO;

namespace LunarDoggo.QuizGame.IO.Test
{
    public class FileQuizQuestionSerializer_275fddd8e9
    {
        private string filePath;
        private FileQuizQuestionSerializer fileQuizQuestionSerializer;

        [SetUp]
        public void Setup()
        {
            filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "TestFile.json"); // TODO: Change the file path as per your requirement
            fileQuizQuestionSerializer = new FileQuizQuestionSerializer(filePath);
        }

        [Test]
        public void DeserializeQuestions_WhenFileExists_ReturnsQuestions()
        {
            IEnumerable<QuizQuestion> questions = fileQuizQuestionSerializer.DeserializeQuestions();
            Assert.IsNotNull(questions);
            Assert.IsNotEmpty(questions);
        }

        [Test]
        public void DeserializeQuestions_WhenFileDoesNotExists_ReturnsEmpty()
        {
            File.Delete(filePath);
            IEnumerable<QuizQuestion> questions = fileQuizQuestionSerializer.DeserializeQuestions();
            Assert.IsNotNull(questions);
            Assert.IsEmpty(questions);
        }
    }
}
