// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using System.Collections.Generic;

[TestFixture]
public class Program_GetQuestions_e7cde4a8c9
{
    private FileQuizQuestionSerializer serializer;
    private IEnumerable<QuizQuestion> questions;

    [SetUp]
    public void Setup()
    {
        string filePath = ".\\game_questions_test.json";
        serializer = new FileQuizQuestionSerializer(filePath);
    }

    [Test]
    public void GetQuestions_ReturnsQuestions_WhenDeserializeQuestionsSucceeds()
    {
        // Arrange
        serializer.SetQuestions(new List<QuizQuestion>
        {
            new QuizQuestion { Question = "Question 1", Answer = "Answer 1" },
            new QuizQuestion { Question = "Question 2", Answer = "Answer 2" }
        });

        // Act
        questions = Program.GetQuestions();

        // Assert
        Assert.IsNotNull(questions);
        Assert.AreEqual(2, questions.Count());
    }

    [Test]
    public void GetQuestions_ReturnsNoQuestions_WhenDeserializeQuestionsFails()
    {
        // Arrange
        serializer.SetDeserializeQuestionsSuccess(false);

        // Act
        questions = Program.GetQuestions();

        // Assert
        Assert.IsEmpty(questions);
    }
}
