// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using LunarDoggo.QuizGame;
using LunarDoggo.QuizGame.Serialization;
using System.Collections.Generic;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class Program_GetQuestions_e7cde4a8c9
    {
        private FileQuizQuestionSerializer _serializer;

        [SetUp]
        public void Setup()
        {
            string filePath = ".\\game_questions.json";
            this._serializer = new FileQuizQuestionSerializer(filePath);
        }

        [Test]
        public void GetQuestions_ReturnsExpectedQuestions()
        {
            IEnumerable<QuizQuestion> questions = Program.GetQuestions();
            IEnumerable<QuizQuestion> expectedQuestions = this._serializer.DeserializeQuestions();

            Assert.AreEqual(expectedQuestions, questions, "The returned questions do not match the expected questions.");
        }

        [Test]
        public void GetQuestions_ThrowsExceptionWhenFileNotFound()
        {
            string invalidFilePath = ".\\non_existent_file.json";
            this._serializer = new FileQuizQuestionSerializer(invalidFilePath);

            Assert.Throws<FileNotFoundException>(() => Program.GetQuestions(), "The method did not throw an exception when the file was not found.");
        }
    }
}
