// Test generated by RoostGPT for test demo5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.IO;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_DrawAnswerStatus_d8bbac5d97
    {
        private StringWriter stringWriter;
        private ConsoleVisualizer consoleVisualizer;

        [SetUp]
        public void SetUp()
        {
            this.stringWriter = new StringWriter();
            Console.SetOut(this.stringWriter);
            this.consoleVisualizer = new ConsoleVisualizer();
        }

        [TearDown]
        public void TearDown()
        {
            this.stringWriter.Close();
            this.stringWriter.Dispose();
        }

        [Test]
        public void DrawAnswerStatus_CorrectAnswer_ProducesCorrectMessage()
        {
            // Arrange
            var correctAnswer = new QuizQuestionAnswer { Answer = "Test Answer" };

            // Act
            this.consoleVisualizer.DrawAnswerStatus(true, correctAnswer);

            // Assert
            var output = this.stringWriter.ToString().Trim();
            Assert.AreEqual("Your answer is correct. Continue with \"enter\".", output);
        }

        [Test]
        public void DrawAnswerStatus_IncorrectAnswer_ProducesCorrectMessage()
        {
            // Arrange
            var correctAnswer = new QuizQuestionAnswer { Answer = "Test Answer" };

            // Act
            this.consoleVisualizer.DrawAnswerStatus(false, correctAnswer);

            // Assert
            var output = this.stringWriter.ToString().Trim();
            Assert.AreEqual(string.Format("Your answer isn't correct. The correct answer is: \"{0}\". Continue with \"enter\".", correctAnswer.Answer), output);
        }
    }
}
