// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;

namespace YourTestNamespace
{
    [TestFixture]
    public class ConsoleVisualizer_DrawAnswerStatus_d8bbac5d97
    {
        [Test]
        public void DrawAnswerStatus_CorrectAnswer_ShouldDisplayCorrectMessage()
        {
            // Arrange
            bool correct = true;
            QuizQuestionAnswer correctAnswer = new QuizQuestionAnswer()
            {
                Answer = "Correct answer"
            };

            // Act
            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw);
                DrawAnswerStatus(correct, correctAnswer);
                string expectedMessage = "Your answer is correct. Continue with \"enter\".";

                // Assert
                Assert.AreEqual(expectedMessage, sw.ToString().Trim());
            }
        }

        [Test]
        public void DrawAnswerStatus_IncorrectAnswer_ShouldDisplayIncorrectMessageWithCorrectAnswer()
        {
            // Arrange
            bool correct = false;
            QuizQuestionAnswer correctAnswer = new QuizQuestionAnswer()
            {
                Answer = "Correct answer"
            };

            // Act
            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw);
                DrawAnswerStatus(correct, correctAnswer);
                string expectedMessage = "Your answer isn't correct. The correct answer is: \"Correct answer\". Continue with \"enter\".";

                // Assert
                Assert.AreEqual(expectedMessage, sw.ToString().Trim());
            }
        }
    }
}
