// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using LunarDoggo.QuizGame;
using System.Collections.Generic;
using System.Linq;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class is_GameState_411dc2bb34
    {
        private GameState _gameState;

        [SetUp]
        public void Setup()
        {
            _gameState = new GameState(new List<QuizQuestion>());
        }

        [Test]
        public void GameState_WithNonNullQuestions_SetsTotalQuestionCount()
        {
            var questions = new List<QuizQuestion> { new QuizQuestion(), new QuizQuestion() };

            _gameState = new GameState(questions);

            Assert.AreEqual(2, _gameState.TotalQuestionCount);
        }

        [Test]
        public void GameState_WithNullQuestions_SetsTotalQuestionCountToZero()
        {
            _gameState = new GameState(null);

            Assert.AreEqual(0, _gameState.TotalQuestionCount);
        }

        [Test]
        public void GameState_WithEmptyQuestions_SetsTotalQuestionCountToZero()
        {
            _gameState = new GameState(new List<QuizQuestion>());

            Assert.AreEqual(0, _gameState.TotalQuestionCount);
        }
    }
}
