// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.Collections.Generic;
using NUnit.Framework;
using LunarDoggo.FileSystemTree;

namespace FileSystemTreeTests
{
    [TestFixture]
    public class FileSystemTreeItemTests
    {
        [Test]
        public void TestFileSystemTreeItemCreation()
        {
            var child1 = new FileSystemTreeItem("Child1", FileSystemTreeItemType.File, null);
            var child2 = new FileSystemTreeItem("Child2", FileSystemTreeItemType.File, null);
            var children = new List<FileSystemTreeItem> { child1, child2 };
            var parent = new FileSystemTreeItem("Parent", FileSystemTreeItemType.Directory, children);

            Assert.AreEqual("Parent", parent.Name);
            Assert.AreEqual(FileSystemTreeItemType.Directory, parent.Type);
            Assert.Contains(child1, parent.Children);
            Assert.Contains(child2, parent.Children);
        }

        [Test]
        public void TestFileSystemTreeItemCreationWithNoChildren()
        {
            var parent = new FileSystemTreeItem("Parent", FileSystemTreeItemType.Directory, null);

            Assert.AreEqual("Parent", parent.Name);
            Assert.AreEqual(FileSystemTreeItemType.Directory, parent.Type);
            Assert.IsEmpty(parent.Children);
        }
    }
}
