// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.Linq;
using LunarDoggo.TicTacToe;

namespace TicTacToeTests
{
    [TestFixture]
    public class MainWindowTests
    {
        [Test]
        public void TestMainWindow_MainWindow_5ff1d40a38()
        {
            // Arrange
            MainWindow mainWindow = new MainWindow();

            // Act
            mainWindow.InitializeComponent();
            mainWindow.buttonTileMappings = mainWindow.GetButtonTileMappings();
            mainWindow.gameState = new GameState(mainWindow.buttonTileMappings);

            // Assert
            Assert.IsNotNull(mainWindow.buttonTileMappings);
            Assert.IsNotNull(mainWindow.gameState);
        }

        [Test]
        public void TestMainWindow_StartGame_5ff1d40a38()
        {
            // Arrange
            MainWindow mainWindow = new MainWindow();
            mainWindow.InitializeComponent();
            mainWindow.buttonTileMappings = mainWindow.GetButtonTileMappings();
            mainWindow.gameState = new GameState(mainWindow.buttonTileMappings);

            // Act
            mainWindow.gameState.StartGame();

            // Assert
            Assert.IsTrue(mainWindow.gameState.GameStarted);
        }
    }
}
