// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using LunarDoggo.QuizGame;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class HighlightNextAnswer_945da34ac1
    {
        [Test]
        public void HighlightNextAnswer_TestWithSingleQuestion()
        {
            var question = new QuizQuestion
            {
                Question = "Test Question",
                Answers = new QuizQuestionAnswer[]
                {
                    new QuizQuestionAnswer { Answer = "Answer 1", IsCorrect = true },
                    new QuizQuestionAnswer { Answer = "Answer 2", IsCorrect = false },
                    new QuizQuestionAnswer { Answer = "Answer 3", IsCorrect = false }
                }
            };

            var gameState = new GameState(new List<QuizQuestion> { question });
            gameState.MoveToNextQuestion();

            gameState.HighlightNextAnswer();

            Assert.AreEqual(question.Answers[1], gameState.HighlightedAnswer);
        }

        [Test]
        public void HighlightNextAnswer_TestWithMultipleQuestions()
        {
            var questions = new List<QuizQuestion>
            {
                new QuizQuestion
                {
                    Question = "Test Question 1",
                    Answers = new QuizQuestionAnswer[]
                    {
                        new QuizQuestionAnswer { Answer = "Answer 1", IsCorrect = true },
                        new QuizQuestionAnswer { Answer = "Answer 2", IsCorrect = false },
                        new QuizQuestionAnswer { Answer = "Answer 3", IsCorrect = false }
                    }
                },
                new QuizQuestion
                {
                    Question = "Test Question 2",
                    Answers = new QuizQuestionAnswer[]
                    {
                        new QuizQuestionAnswer { Answer = "Answer 1", IsCorrect = false },
                        new QuizQuestionAnswer { Answer = "Answer 2", IsCorrect = true },
                        new QuizQuestionAnswer { Answer = "Answer 3", IsCorrect = false }
                    }
                }
            };

            var gameState = new GameState(questions);
            gameState.MoveToNextQuestion();

            gameState.HighlightNextAnswer();

            Assert.AreEqual(questions[0].Answers[1], gameState.HighlightedAnswer);
        }
    }
}
