// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;
using Moq;
using System.IO;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_DrawGameStart_a42d8b8ea3
    {
        private StringWriter _stringWriter;
        private TextWriter _originalOutput;

        [SetUp]
        public void SetUp()
        {
            _stringWriter = new StringWriter();
            _originalOutput = Console.Out;
            Console.SetOut(_stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            Console.SetOut(_originalOutput);
            _stringWriter.Dispose();
        }

        [Test]
        public void DrawGameStart_SingleQuestion_DisplayCorrectMessage()
        {
            // Arrange
            var totalQuestionCount = 1;
            var expectedOutput = $"1 question was loaded, press \"enter\" to start the game.\r\n";

            // Act
            DrawGameStart(totalQuestionCount);

            // Assert
            Assert.AreEqual(expectedOutput, _stringWriter.ToString());
        }

        [Test]
        public void DrawGameStart_MultipleQuestions_DisplayCorrectMessage()
        {
            // Arrange
            var totalQuestionCount = 5;
            var expectedOutput = $"5 questions were loaded, press \"enter\" to start the game.\r\n";

            // Act
            DrawGameStart(totalQuestionCount);

            // Assert
            Assert.AreEqual(expectedOutput, _stringWriter.ToString());
        }

        public void DrawGameStart(int totalQuestionCount)
        {
            Console.Clear();
            Console.WriteLine("{0} question{1} {2} loaded, press \"enter\" to start the game.", totalQuestionCount, totalQuestionCount > 1 ? "s" : "", totalQuestionCount > 1 ? "were" : "was");
        }
    }
}
