// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.IO;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_55b6cef3d0
    {
        private StringWriter stringWriter;
        private ConsoleVisualizer consoleVisualizer;

        [SetUp]
        public void Setup()
        {
            this.stringWriter = new StringWriter();
            Console.SetOut(this.stringWriter);
            this.consoleVisualizer = new ConsoleVisualizer();
        }

        [TearDown]
        public void TearDown()
        {
            this.stringWriter.Close();
        }

        [Test]
        public void DrawNoQuestions_WritesExpectedMessageToConsole()
        {
            this.consoleVisualizer.DrawNoQuestions();

            var expected = "No questions were loaded, please enter some questions into the json file in the applications folder.\n\nReload game? (Y/N)\r\n";
            Assert.AreEqual(expected, this.stringWriter.ToString());
        }

        [Test]
        public void DrawGameStart_WritesExpectedMessageToConsole()
        {
            var totalQuestionCount = 5;
            this.consoleVisualizer.DrawGameStart(totalQuestionCount);

            var expected = "5 questions were loaded, press \"enter\" to start the game.\r\n";
            Assert.AreEqual(expected, this.stringWriter.ToString());
        }

        // TODO: Continue with other test cases for each public method in the ConsoleVisualizer class.
    }
}
