// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;
using System.IO;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_55b6cef3d0
    {
        private ConsoleVisualizer consoleVisualizer;
        private StringWriter stringWriter;

        [SetUp]
        public void SetUp()
        {
            consoleVisualizer = new ConsoleVisualizer();
            stringWriter = new StringWriter();
            Console.SetOut(stringWriter);
        }

        [Test]
        public void ConsoleVisualizer_CursorVisibleIsFalse()
        {
            Assert.IsFalse(Console.CursorVisible);
        }

        [Test]
        public void DrawNoQuestions_MessageIsCorrect()
        {
            consoleVisualizer.DrawNoQuestions();
            string expectedMessage = "No questions were loaded, please enter some questions into the json file in the applications folder.\n\nReload game? (Y/N)\r\n";
            Assert.AreEqual(expectedMessage, stringWriter.ToString());
        }

        // TODO: Add more test cases for other methods in ConsoleVisualizer class

        [TearDown]
        public void TearDown()
        {
            stringWriter.Dispose();
        }
    }
}
