// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;

// Ensure to reference the correct namespace for Button
// If you're using WPF, it should be System.Windows.Controls
// If you're using WinForms, it should be System.Windows.Forms
using System.Windows.Forms;
using TicTacToe;

namespace TicTacToe.Tests
{
    [TestFixture]
    public class ButtonTileMappingTests
    {
        [Test]
        public void TestButtonTileMapping_ButtonTileMapping_bc2b2b3fdf()
        {
            // Arrange
            Button button = new Button();
            int tileX = 1;
            int tileY = 2;

            // Act
            ButtonTileMapping mapping = new ButtonTileMapping(button, tileX, tileY);

            // Assert
            Assert.AreEqual(button, mapping.Button);
            Assert.AreEqual(tileX, mapping.TileX);
            Assert.AreEqual(tileY, mapping.TileY);
        }

        [Test]
        public void TestButtonTileMapping_ButtonTileMapping_NullButton()
        {
            // Arrange
            Button button = null;
            int tileX = 1;
            int tileY = 2;

            // Act
            var ex = Assert.Throws<ArgumentNullException>(() => new ButtonTileMapping(button, tileX, tileY));

            // Assert
            StringAssert.Contains("button", ex.Message);
        }
    }
}
