// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System;
using LunarDoggo.QuizGame.Visuals;
using NUnit.Framework;

namespace LunarDoggo.QuizGame.Visuals.Tests
{
    [TestFixture]
    public class ConsoleVisualizerTests
    {
        private ConsoleVisualizer visualizer;

        [SetUp]
        public void Setup()
        {
            visualizer = new ConsoleVisualizer();
        }

        [Test]
        public void TestConsoleVisualizer_DrawNoQuestions_263b5c9064()
        {
            // Arrange
            string expectedMessage = "No questions were loaded, please enter some questions into the json file in the applications folder.\n\nReload game? (Y/N)";
            string actualMessage;

            // Act
            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw);
                visualizer.DrawNoQuestions();
                actualMessage = sw.ToString().Trim();
            }

            // Assert
            Assert.AreEqual(expectedMessage, actualMessage);
        }
    }
}
