// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.IO;
using LunarDoggo.QuizGame.Visuals;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_DrawNoQuestions_263b5c9064
    {
        private StringWriter _stringWriter;
        private ConsoleVisualizer _consoleVisualizer;

        [SetUp]
        public void SetUp()
        {
            _stringWriter = new StringWriter();
            Console.SetOut(_stringWriter);
            _consoleVisualizer = new ConsoleVisualizer();
        }

        [Test]
        public void DrawNoQuestions_MessageIsCorrect()
        {
            _consoleVisualizer.DrawNoQuestions();

            string expected = "No questions were loaded, please enter some questions into the json file in the applications folder.\n\nReload game? (Y/N)\r\n";
            Assert.AreEqual(expected, _stringWriter.ToString());
        }

        [TearDown]
        public void TearDown()
        {
            _stringWriter.Close();
        }
    }
}
