// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;

namespace LunarDoggo.TicTacToe.Test
{
    [TestFixture]
    public class GameBoardTests
    {
        private GameBoard _gameBoard;

        [SetUp]
        public void SetUp()
        {
            _gameBoard = new GameBoard();
        }

        [Test]
        public void TestGameBoard_Reset_87856d81fa()
        {
            // Arrange
            _gameBoard.tiles[0, 0] = 1;
            _gameBoard.tiles[1, 1] = 2;
            _gameBoard.tiles[2, 2] = 1;

            // Act
            _gameBoard.Reset();

            // Assert
            for (int x = 0; x < _gameBoard.tiles.GetLength(0); x++)
            {
                for (int y = 0; y < _gameBoard.tiles.GetLength(1); y++)
                {
                    Assert.AreEqual(0, _gameBoard.tiles[x, y]);
                }
            }
        }

        [Test]
        public void TestGameBoard_Reset_EmptyBoard_87856d81fa()
        {
            // Arrange
            // No need to arrange anything as the board is already empty

            // Act
            _gameBoard.Reset();

            // Assert
            for (int x = 0; x < _gameBoard.tiles.GetLength(0); x++)
            {
                for (int y = 0; y < _gameBoard.tiles.GetLength(1); y++)
                {
                    Assert.AreEqual(0, _gameBoard.tiles[x, y]);
                }
            }
        }
    }
}
