// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.Linq;
using NUnit.Framework;

namespace LunarDoggo.TicTacToe.Test
{
    [TestFixture]
    public class MainWindowTests
    {
        private MainWindow _mainWindow;

        [SetUp]
        public void SetUp()
        {
            _mainWindow = new MainWindow();
        }

        [Test]
        public void TestMainWindow_GetButtonTileMappings_855bdcb083()
        {
            var result = _mainWindow.GetButtonTileMappings();

            Assert.AreEqual(9, result.Length);

            AssertButtonTileMapping(result[0], _mainWindow.btnTopLeft, 0, 0);
            AssertButtonTileMapping(result[1], _mainWindow.btnTopCenter, 1, 0);
            AssertButtonTileMapping(result[2], _mainWindow.btnTopRight, 2, 0);
            AssertButtonTileMapping(result[3], _mainWindow.btnMiddleLeft, 0, 1);
            AssertButtonTileMapping(result[4], _mainWindow.btnMiddleCenter, 1, 1);
            AssertButtonTileMapping(result[5], _mainWindow.btnMiddleRight, 2, 1);
            AssertButtonTileMapping(result[6], _mainWindow.btnBottomLeft, 0, 2);
            AssertButtonTileMapping(result[7], _mainWindow.btnBottomCenter, 1, 2);
            AssertButtonTileMapping(result[8], _mainWindow.btnBottomRight, 2, 2);
        }

        private void AssertButtonTileMapping(object actual, object expectedButton, int expectedX, int expectedY)
        {
            Assert.AreEqual(expectedButton, actual);
            Assert.AreEqual(expectedX, actual);
            Assert.AreEqual(expectedY, actual);
        }
    }
}
