// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using LunarDoggo.QuizGame;
using System.Collections.Generic;
using System.Linq;
using System;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class MoveToNextQuestion_2455d33844
    {
        private GameState _gameState;
        private QuizQuestion _question1;
        private QuizQuestion _question2;

        [SetUp]
        public void Setup()
        {
            _question1 = new QuizQuestion { Question = "Question 1", Answers = new QuizQuestionAnswer[] { new QuizQuestionAnswer { Answer = "Answer 1", IsCorrect = true } } };
            _question2 = new QuizQuestion { Question = "Question 2", Answers = new QuizQuestionAnswer[] { new QuizQuestionAnswer { Answer = "Answer 2", IsCorrect = false } } };
            _gameState = new GameState(new List<QuizQuestion> { _question1, _question2 });
        }

        [Test]
        public void MoveToNextQuestion_WhenThereAreUnansweredQuestions_ChangesCurrentQuestion()
        {
            // Act
            _gameState.MoveToNextQuestion();

            // Assert
            Assert.That(_gameState.CurrentQuestion, Is.Not.Null);
            Assert.That(_gameState.CurrentQuestion, Is.EqualTo(_question1).Or.EqualTo(_question2));
        }

        [Test]
        public void MoveToNextQuestion_WhenThereAreNoUnansweredQuestions_DoesNotChangeCurrentQuestion()
        {
            // Arrange
            _gameState.MoveToNextQuestion();
            _gameState.AnswerQuestion();
            _gameState.MoveToNextQuestion();
            _gameState.AnswerQuestion();

            // Act
            _gameState.MoveToNextQuestion();

            // Assert
            Assert.That(_gameState.CurrentQuestion, Is.Null);
        }
    }
}
