// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using System;
using System.Collections.Generic;
using NUnit.Framework;
using Moq;
using LunarDoggo.QuizGame;

namespace LunarDoggo.QuizGame.Test
{
    public class contains_GameLoop_7089a8196a
    {
        private Mock<IVisualizer> visualizerMock;
        private IEnumerable<QuizQuestion> questions;

        [SetUp]
        public void Setup()
        {
            visualizerMock = new Mock<IVisualizer>();
            questions = new List<QuizQuestion>()
            {
                new QuizQuestion("Question 1", "Answer 1"),
                new QuizQuestion("Question 2", "Answer 2")
            };
        }

        [Test]
        public void GameLoop_Constructor_Successful()
        {
            var gameLoop = new GameLoop(visualizerMock.Object, questions);
            Assert.IsNotNull(gameLoop);
        }

        [Test]
        public void GameLoop_Constructor_NullVisualizer_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new GameLoop(null, questions));
        }

        [Test]
        public void GameLoop_Constructor_NullQuestions_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new GameLoop(visualizerMock.Object, null));
        }
        
        [Test]
        public void GameLoop_Constructor_EmptyQuestions_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new GameLoop(visualizerMock.Object, new List<QuizQuestion>()));
        }
    }
}
