// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;
using System.IO;

namespace LunarDoggo.QuizGame.Visuals.Tests
{
    [TestFixture]
    public class DrawNoQuestions_a3570fb089
    {
        private ConsoleVisualizer consoleVisualizer;
        private StringWriter stringWriter;

        [SetUp]
        public void SetUp()
        {
            consoleVisualizer = new ConsoleVisualizer();
            stringWriter = new StringWriter();
            Console.SetOut(stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            stringWriter.Close();
            stringWriter.Dispose();
        }

        [Test]
        public void DrawNoQuestions_MessageAppearsInConsoleOutput()
        {
            consoleVisualizer.DrawNoQuestions();
            string consoleOutput = stringWriter.ToString();
            Assert.IsTrue(consoleOutput.Contains("No questions were loaded, please enter some questions into the json file in the applications folder.\n\nReload game? (Y/N)"));
        }

        [Test]
        public void DrawNoQuestions_WhenCalled_CursorIsNotVisible()
        {
            consoleVisualizer.DrawNoQuestions();
            Assert.IsFalse(Console.CursorVisible);
        }
    }
}
