// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using System;
using System.IO;
using LunarDoggo.QuizGame.Visuals;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawNoQuestions_a3570fb089
    {
        private ConsoleVisualizer visualizer;

        [SetUp]
        public void SetUp()
        {
            visualizer = new ConsoleVisualizer();
        }

        [Test]
        public void DrawNoQuestions_WhenCalled_ShouldPrintExpectedMessageToConsole()
        {
            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw);

                visualizer.DrawNoQuestions();

                string expected = "No questions were loaded, please enter some questions into the json file in the applications folder.\n\nReload game? (Y/N)" + Environment.NewLine;
                Assert.AreEqual(expected, sw.ToString());
            }
        }

        [Test]
        public void DrawNoQuestions_WhenCalled_ShouldNotChangeConsoleCursorPosition()
        {
            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw);
                int expectedTop = Console.CursorTop;
                int expectedLeft = Console.CursorLeft;

                visualizer.DrawNoQuestions();

                Assert.AreEqual(expectedTop, Console.CursorTop);
                Assert.AreEqual(expectedLeft, Console.CursorLeft);
            }
        }
    }
}
