// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.IO;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawPlayAgain_0355656c5f
    {
        private ConsoleVisualizer consoleVisualizer;
        private StringWriter stringWriter;

        [SetUp]
        public void SetUp()
        {
            this.consoleVisualizer = new ConsoleVisualizer();
            this.stringWriter = new StringWriter();
            Console.SetOut(this.stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            this.stringWriter.Close();
            this.stringWriter.Dispose();
        }

        [Test]
        public void DrawPlayAgain_WritesExpectedMessageToConsole()
        {
            // Act
            this.consoleVisualizer.DrawPlayAgain();

            // Assert
            var expected = "Do you like to play again? (Y/N)" + Environment.NewLine;
            Assert.AreEqual(expected, this.stringWriter.ToString());
        }

        [Test]
        public void DrawPlayAgain_WritesOnlyOneLineToConsole()
        {
            // Act
            this.consoleVisualizer.DrawPlayAgain();

            // Assert
            var lines = this.stringWriter.ToString().Split(Environment.NewLine);
            Assert.AreEqual(2, lines.Length); // One line of message and one line of newline character
        }
    }
}
