// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;
using LunarDoggo.TicTacToe; // Updated namespace

namespace LunarDoggo.TicTacToe.Tests // Updated namespace
{
    [TestFixture]
    public class GameBoardTests
    {
        private Player player1;
        private Player player2;
        private GameBoard gameBoard;

        [SetUp]
        public void SetUp()
        {
            player1 = new Player { Id = 1, Name = "Player 1" };
            player2 = new Player { Id = 2, Name = "Player 2" };
            gameBoard = new GameBoard();
        }

        [Test]
        public void TestGameBoard_OccupyTile_c3c53eadf5()
        {
            // Test case 1: Check if a player can occupy an unoccupied tile
            bool result1 = gameBoard.OccupyTile(player1, 0, 0);
            Assert.IsTrue(result1, "Player should be able to occupy an unoccupied tile");

            // Test case 2: Check if a player can occupy an already occupied tile
            bool result2 = gameBoard.OccupyTile(player2, 0, 0);
            Assert.IsFalse(result2, "Player should not be able to occupy an already occupied tile");

            // Test case 3: Check if a player can occupy a tile outside of the board
            bool result3 = gameBoard.OccupyTile(player1, 5, 5);
            Assert.IsFalse(result3, "Player should not be able to occupy a tile outside of the board");
        }
    }
}
