// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;

[TestFixture]
public class Test_Class
{
    private ClassToTest objectUnderTest;

    [SetUp]
    public void SetUp()
    {
        objectUnderTest = new ClassToTest();
    }

    [Test]
    public void DoTick_StateHasUnansweredQuestions_ShouldNotBeFinished()
    {
        // Arrange
        objectUnderTest.state.HasUnansweredQuestions = true;

        // Act
        objectUnderTest.DoTick();

        // Assert
        Assert.IsFalse(objectUnderTest.IsFinished);
    }

    [Test]
    public void DoTick_StateHasNoUnansweredQuestions_ShouldBeFinished()
    {
        // Arrange
        objectUnderTest.state.HasUnansweredQuestions = false;

        // Act
        objectUnderTest.DoTick();

        // Assert
        Assert.IsTrue(objectUnderTest.IsFinished);
    }
}
