// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using Moq;
using LunarDoggo.QuizGame;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class contains_DoTick_d07eab7cbf
    {
        private Mock<GameState> mockGameState;
        private Game game;

        [SetUp]
        public void SetUp()
        {
            // TODO: Initialize the mock object and the game object
            this.mockGameState = new Mock<GameState>();
            this.game = new Game(this.mockGameState.Object);
        }

        [Test]
        public void DoTick_GameNotFinished_UpdatesScreenAndProcessesInput()
        {
            // Arrange
            this.mockGameState.Setup(state => state.HasUnansweredQuestions).Returns(true);

            // Act
            this.game.DoTick();

            // Assert
            Assert.That(this.game.IsFinished, Is.False);
            this.mockGameState.Verify(state => state.UpdateScreen(), Times.Once);
            this.mockGameState.Verify(state => state.ProcessInput(), Times.Once);
        }

        [Test]
        public void DoTick_GameFinished_SetsIsFinishedToTrue()
        {
            // Arrange
            this.mockGameState.Setup(state => state.HasUnansweredQuestions).Returns(false);

            // Act
            this.game.DoTick();

            // Assert
            Assert.That(this.game.IsFinished, Is.True);
            this.mockGameState.Verify(state => state.UpdateScreen(), Times.Once);
            this.mockGameState.Verify(state => state.ProcessInput(), Times.Once);
        }

        [TearDown]
        public void TearDown()
        {
            // TODO: Clean up any resources used during testing
            this.mockGameState = null;
            this.game = null;
        }
    }
}
