// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using LunarDoggo.QuizGame;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class GameState_3381fc8da9
    {
        private GameState gameState;
        private List<QuizQuestion> questions;

        [SetUp]
        public void Setup()
        {
            this.questions = new List<QuizQuestion>
            {
                new QuizQuestion { Question = "Question1", Answers = new QuizQuestionAnswer[] { new QuizQuestionAnswer { IsCorrect = true } } },
                new QuizQuestion { Question = "Question2", Answers = new QuizQuestionAnswer[] { new QuizQuestionAnswer { IsCorrect = false } } }
            };
        }

        [Test]
        public void GameState_Constructor_Should_Initialize_With_Valid_Questions()
        {
            this.gameState = new GameState(this.questions);

            Assert.AreEqual(this.questions.Count, this.gameState.TotalQuestionCount);
            Assert.IsTrue(this.gameState.HasUnansweredQuestions);
        }

        [Test]
        public void GameState_Constructor_Should_Initialize_Without_Questions()
        {
            this.gameState = new GameState(null);

            Assert.AreEqual(0, this.gameState.TotalQuestionCount);
            Assert.IsFalse(this.gameState.HasUnansweredQuestions);
        }
    }
}
