// Test generated by RoostGPT for test demo56 using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;

namespace TicTacToeTests
{
    public class Player
    {
        public Player(string name, string symbol)
        {
            Name = name;
            Symbol = symbol;
        }

        public string Name { get; }
        public string Symbol { get; }
    }

    public class PlayerTileEventArgs : EventArgs
    {
        public PlayerTileEventArgs(Player player, int tileX, int tileY)
        {
            Player = player;
            TileX = tileX;
            TileY = tileY;
        }

        public Player Player { get; }
        public int TileX { get; }
        public int TileY { get; }
    }

    [TestFixture]
    public class PlayerTileEventArgsTests
    {
        [Test]
        public void Testis_PlayerTileEventArgs_ValidInput()
        {
            // Arrange
            Player player = new Player("Player1", "X");
            int tileX = 1;
            int tileY = 2;

            // Act
            PlayerTileEventArgs playerTileEventArgs = new PlayerTileEventArgs(player, tileX, tileY);

            // Assert
            Assert.AreEqual(player, playerTileEventArgs.Player);
            Assert.AreEqual(tileX, playerTileEventArgs.TileX);
            Assert.AreEqual(tileY, playerTileEventArgs.TileY);
        }

        [Test]
        public void Testis_PlayerTileEventArgs_NullPlayer()
        {
            // Arrange
            Player player = null;
            int tileX = 1;
            int tileY = 2;

            // Act
            PlayerTileEventArgs playerTileEventArgs = new PlayerTileEventArgs(player, tileX, tileY);

            // Assert
            Assert.IsNull(playerTileEventArgs.Player);
            Assert.AreEqual(tileX, playerTileEventArgs.TileX);
            Assert.AreEqual(tileY, playerTileEventArgs.TileY);
        }
    }
}
