// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.Linq;
using NUnit.Framework;
using LunarDoggo.TicTacToe; // Assuming Game and Player classes are in this namespace

namespace TicTacToe
{
    [TestFixture]
    public class TestSuite
    {
        private Game game;
        private Player firstPlayer;

        [SetUp]
        public void SetUp()
        {
            firstPlayer = new Player();
            game = new Game(firstPlayer, new Player());
        }

        [Test]
        public void TestGameState_StartGame_4a812ccee3()
        {
            game.StartGame();

            Assert.AreEqual(firstPlayer, game.CurrentPlayer);
            Assert.IsTrue(game.Board.All(tile => tile == null));
            Assert.IsNull(game.TilesReset);
        }

        [Test]
        public void TestGameState_StartGame_WithTilesReset_4a812ccee3()
        {
            bool eventRaised = false;
            game.TilesReset += (sender, args) => eventRaised = true;

            game.StartGame();

            Assert.IsTrue(eventRaised);
        }
    }
}
