// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.IO;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawQuizQuestion_1d352aaa00
    {
        private ConsoleVisualizer consoleVisualizer;
        private StringWriter stringWriter;
        private QuizQuestion quizQuestion;
        private Guid highlitedAnswerId;

        [SetUp]
        public void SetUp()
        {
            consoleVisualizer = new ConsoleVisualizer();
            stringWriter = new StringWriter();
            Console.SetOut(stringWriter);

            quizQuestion = new QuizQuestion
            {
                Question = "What is the capital of Australia?",
                Answers = new QuizQuestionAnswer[]
                {
                    new QuizQuestionAnswer { Id = Guid.NewGuid(), Answer = "Sydney" },
                    new QuizQuestionAnswer { Id = Guid.NewGuid(), Answer = "Melbourne" },
                    new QuizQuestionAnswer { Id = highlitedAnswerId = Guid.NewGuid(), Answer = "Canberra" },
                    new QuizQuestionAnswer { Id = Guid.NewGuid(), Answer = "Brisbane" }
                }
            };
        }

        [Test]
        public void DrawQuizQuestion_HighlightedAnswerExists_HighlightedAnswerIsMarked()
        {
            consoleVisualizer.DrawQuizQuestion(quizQuestion, highlitedAnswerId);

            StringAssert.Contains("(*) Canberra", stringWriter.ToString());
        }

        [Test]
        public void DrawQuizQuestion_HighlightedAnswerDoesNotExist_NoAnswerIsMarked()
        {
            consoleVisualizer.DrawQuizQuestion(quizQuestion, Guid.NewGuid());

            StringAssert.DoesNotContain("(*)", stringWriter.ToString());
        }

        [TearDown]
        public void TearDown()
        {
            stringWriter.Close();
        }
    }
}
