// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using System;
using System.IO;
using NUnit.Framework;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    public class ConsoleVisualizer_DrawGameResult_189e648b4a
    {
        private StringWriter stringWriter;

        [SetUp]
        public void SetUp()
        {
            stringWriter = new StringWriter();
            Console.SetOut(stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            stringWriter.Close();
        }

        [Test]
        public void DrawGameResult_CorrectAnswersCountIsLessThanTotalQuestionCount_PrintsCorrectMessage()
        {
            // Arrange
            int totalQuestionCount = 5;
            int correctAnswersCount = 3;
            string expectedOutput = $"You got {correctAnswersCount} out of {totalQuestionCount} question right. Continue with \"enter\".\r\n\r\n";

            // Act
            DrawGameResult(totalQuestionCount, correctAnswersCount);

            // Assert
            Assert.AreEqual(expectedOutput, stringWriter.ToString());
        }

        [Test]
        public void DrawGameResult_CorrectAnswersCountIsEqualToTotalQuestionCount_PrintsCorrectMessage()
        {
            // Arrange
            int totalQuestionCount = 5;
            int correctAnswersCount = 5;
            string expectedOutput = $"You got {correctAnswersCount} out of {totalQuestionCount} question right. Continue with \"enter\".\r\n\r\n";

            // Act
            DrawGameResult(totalQuestionCount, correctAnswersCount);

            // Assert
            Assert.AreEqual(expectedOutput, stringWriter.ToString());
        }

        public void DrawGameResult(int totalQuestionCount, int correctAnswersCount)
        {
            Console.WriteLine("You got {0} out of {1} question right. Continue with \"enter\".", correctAnswersCount, totalQuestionCount);
            Console.WriteLine();
        }
    }
}
