// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    public class ConsoleVisualizer_ConsoleVisualizer_9d5cdeeb71
    {
        private ConsoleVisualizer _consoleVisualizer;

        [SetUp]
        public void Setup()
        {
            _consoleVisualizer = new ConsoleVisualizer();
        }

        [Test]
        public void ConsoleVisualizer_CursorIsInvisibleOnCreation()
        {
            Assert.IsFalse(Console.CursorVisible);
        }

        [Test]
        public void ConsoleVisualizer_CursorIsVisibleAfterSetting()
        {
            Console.CursorVisible = true;

            Assert.IsTrue(Console.CursorVisible);
        }
    }
}
