// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System;
using System.Collections.Generic;
using System.Linq;
using LunarDoggo.FileSystemTree;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace LunarDoggo.FileSystemTree.Tests
{
    [TestClass]
    public class FileSystemTreeTests
    {
        [TestMethod]
        public void TestOutputFileSystemTreeLevel()
        {
            FileSystemTreeItem rootItem = GenerateFileSystemTree();
            Program.OutputFileSystemTreeLevel(0, rootItem);
        }

        [TestMethod]
        public void TestOutputFileSystemTreeLevel_InvalidItem()
        {
            FileSystemTreeItem invalidItem = null;
            Program.OutputFileSystemTreeLevel(0, invalidItem);
        }

        private FileSystemTreeItem GenerateFileSystemTree()
        {
            FileSystemTreeItem rootItem = new FileSystemTreeItem("Root", FileSystemItemType.Directory);
            FileSystemTreeItem child1 = new FileSystemTreeItem("Child1", FileSystemItemType.File);
            FileSystemTreeItem child2 = new FileSystemTreeItem("Child2", FileSystemItemType.Directory);
            FileSystemTreeItem grandchild1 = new FileSystemTreeItem("Grandchild1", FileSystemItemType.File);
            FileSystemTreeItem grandchild2 = new FileSystemTreeItem("Grandchild2", FileSystemItemType.Directory);

            rootItem.AddChild(child1);
            rootItem.AddChild(child2);

            child2.AddChild(grandchild1);
            child2.AddChild(grandchild2);

            return rootItem;
        }
    }
}
