// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System;
using NUnit.Framework;
using LunarDoggo.FileSystemTree;

namespace LunarDoggo.FileSystemTree.Tests
{
    [TestFixture]
    public class ProgramTests
    {
        [Test]
        public void TestProgram_GetFileSystemTree_fd7daa2836()
        {
            DirectoryInfo baseDirectory = new DirectoryInfo(@"C:\TestDirectory"); // TODO: Replace with actual directory for testing

            FileSystemTreeItem result = Program.GetFileSystemTree(baseDirectory);

            Assert.IsNotNull(result);
            Assert.AreEqual(baseDirectory.Name, result.Name);
            Assert.AreEqual(FileSystemTreeItemType.Directory, result.Type);
            Assert.IsTrue(result.Children.Any());
        }

        [Test]
        public void TestProgram_GetFileSystemTree_fd7daa2836_WithInvalidDirectory()
        {
            DirectoryInfo baseDirectory = new DirectoryInfo(@"C:\NonExistentDirectory"); // TODO: Replace with actual directory for testing

            var ex = Assert.Throws<DirectoryNotFoundException>(() => Program.GetFileSystemTree(baseDirectory));

            Assert.That(ex.Message, Is.EqualTo("Could not find a part of the path 'C:\\NonExistentDirectory'."));
        }
    }
}
