// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.Linq;
using NUnit.Framework;

namespace TicTacToe
{
    [TestFixture]
    public class OnTileAlreadyOccupiedTests
    {
        [Test]
        public void TestMainWindow_OnTileAlreadyOccupied_79f7726c77()
        {
            var main = new MainWindow();

            using (new MessageBoxInterceptor("This space is already occupied, please choose another one.", "Can't occupy"))
            {
                main.OnTileAlreadyOccupied(this, EventArgs.Empty);
            }
        }

        [Test]
        public void TestMainWindow_OnTileAlreadyOccupied_79f7726c77_FailureCase()
        {
            var main = new MainWindow();

            using (new MessageBoxInterceptor("Wrong message", "Can't occupy"))
            {
                Assert.Throws<AssertionException>(() => main.OnTileAlreadyOccupied(this, EventArgs.Empty));
            }
        }
    }

    public class MessageBoxInterceptor : IDisposable
    {
        private string _expectedMessage;
        private string _expectedCaption;

        public MessageBoxInterceptor(string expectedMessage, string expectedCaption)
        {
            _expectedMessage = expectedMessage;
            _expectedCaption = expectedCaption;
        }

        public void Dispose()
        {
        }
    }
}
