// Test generated by RoostGPT for test test-dummy using AI Type Open AI and AI Model gpt-4

using System;
using System.Linq;
using NUnit.Framework;
// Replace LunarDoggo.TicTacToe with the correct namespace where your GameState class is located
using CorrectNamespace;

namespace TicTacToeTests
{
    [TestFixture]
    public class GameStateTests
    {
        [Test]
        public void TestGameState_GameState_cf2d9ec048()
        {
            // Arrange
            var buttonTileMappings = new ButtonTileMapping[]
            {
                new ButtonTileMapping(1, "Button1"),
                new ButtonTileMapping(2, "Button2"),
                new ButtonTileMapping(3, "Button3")
            };

            // Act
            var gameState = new GameState(buttonTileMappings);

            // Assert
            Assert.IsNotNull(gameState);
            Assert.AreEqual(3, gameState.buttonTileMappings.Length);
            Assert.AreEqual("X", gameState.firstPlayer.Symbol);
            Assert.AreEqual("O", gameState.secondPlayer.Symbol);
            Assert.IsNotNull(gameState.gameBoard);
        }

        [Test]
        public void TestGameState_GameState_NullButtonTileMappings_cf2d9ec048()
        {
            // Arrange
            ButtonTileMapping[] buttonTileMappings = null;

            // Act and Assert
            Assert.Throws<ArgumentNullException>(() => new GameState(buttonTileMappings));
        }
    }
}
