// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;

namespace YourNamespace.Tests
{
    [TestFixture]
    public class ConsoleVisualizer_DrawQuizQuestionAnswerTests
    {
        [Test]
        public void DrawQuizQuestionAnswer_ShouldWriteHighlightedAnswer()
        {
            // Arrange
            QuizQuestionAnswer answer = new QuizQuestionAnswer { Answer = "Answer 1" };
            bool highlighted = true;

            // Act
            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw); // Redirect console output to a StringWriter
                DrawQuizQuestionAnswer(answer, highlighted);
                string consoleOutput = sw.ToString().Trim();

                // Assert
                Assert.AreEqual("(*) Answer 1", consoleOutput);
            }
        }

        [Test]
        public void DrawQuizQuestionAnswer_ShouldWriteUnhighlightedAnswer()
        {
            // Arrange
            QuizQuestionAnswer answer = new QuizQuestionAnswer { Answer = "Answer 2" };
            bool highlighted = false;

            // Act
            using (StringWriter sw = new StringWriter())
            {
                Console.SetOut(sw); // Redirect console output to a StringWriter
                DrawQuizQuestionAnswer(answer, highlighted);
                string consoleOutput = sw.ToString().Trim();

                // Assert
                Assert.AreEqual("( ) Answer 2", consoleOutput);
            }
        }
    }
}
