// Test generated by RoostGPT for test test-csrepo using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;
using System;
using System.IO;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class ConsoleVisualizer_DrawQuizQuestionAnswer_f4751de21c
    {
        private StringWriter stringWriter;

        [SetUp]
        public void Setup()
        {
            this.stringWriter = new StringWriter();
            Console.SetOut(this.stringWriter);
        }

        [TearDown]
        public void TearDown()
        {
            this.stringWriter.Close();
        }

        [Test]
        public void DrawQuizQuestionAnswer_HighlightedAnswer_WritesAnswerWithAsterisk()
        {
            var visualizer = new ConsoleVisualizer();
            var answer = new QuizQuestionAnswer { Answer = "Test Answer" };

            visualizer.DrawQuizQuestionAnswer(answer, true);

            var expectedOutput = "(*) Test Answer\r\n";
            Assert.AreEqual(expectedOutput, this.stringWriter.ToString());
        }

        [Test]
        public void DrawQuizQuestionAnswer_NotHighlightedAnswer_WritesAnswerWithSpace()
        {
            var visualizer = new ConsoleVisualizer();
            var answer = new QuizQuestionAnswer { Answer = "Test Answer" };

            visualizer.DrawQuizQuestionAnswer(answer, false);

            var expectedOutput = "( ) Test Answer\r\n";
            Assert.AreEqual(expectedOutput, this.stringWriter.ToString());
        }
    }
}
