// Test generated by RoostGPT for test demo5 using AI Type Open AI and AI Model gpt-4

using System;
using System.IO;
using NUnit.Framework;
using LunarDoggo.QuizGame;
using Moq;

namespace LunarDoggo.QuizGame.Test
{
    [TestFixture]
    public class contains_ProcessInput_f8772fcbcb
    {
        private StringWriter stringWriter;
        private StringReader stringReader;
        private Mock<IQuizGame> quizGameMock; 

        [SetUp]
        public void SetUp()
        {
            this.stringWriter = new StringWriter();
            Console.SetOut(stringWriter);

            this.quizGameMock = new Mock<IQuizGame>(); 
        }

        [TearDown]
        public void TearDown()
        {
            this.stringWriter.Close();
            this.stringReader?.Close();
        }

        [Test]
        public void Test_ProcessInput_UpArrow()
        {
            this.stringReader = new StringReader(Convert.ToString((char)ConsoleKey.UpArrow));
            Console.SetIn(stringReader);

            quizGameMock.Object.ProcessInput();

            quizGameMock.Verify(mock => mock.ChangeHighlightedAnswer(true), Times.Once());
        }

        [Test]
        public void Test_ProcessInput_DownArrow()
        {
            this.stringReader = new StringReader(Convert.ToString((char)ConsoleKey.DownArrow));
            Console.SetIn(stringReader);

            quizGameMock.Object.ProcessInput();

            quizGameMock.Verify(mock => mock.ChangeHighlightedAnswer(false), Times.Once());
        }

        [Test]
        public void Test_ProcessInput_Enter()
        {
            this.stringReader = new StringReader(Convert.ToString((char)ConsoleKey.Enter));
            Console.SetIn(stringReader);

            quizGameMock.Object.ProcessInput();

            quizGameMock.Verify(mock => mock.ProcessEnterPress(), Times.Once());
        }
    }
}
