// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.IO;
using NUnit.Framework;
using LunarDoggo.QuizGame.Visuals;

namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawAnswerStatus_27e98f06a4
    {
        private ConsoleVisualizer visualizer;
        private StringWriter stringWriter;

        [SetUp]
        public void Setup()
        {
            this.stringWriter = new StringWriter();
            Console.SetOut(this.stringWriter);
            this.visualizer = new ConsoleVisualizer();
        }

        [Test]
        public void DrawAnswerStatus_CorrectAnswer_ShouldDisplayCorrectMessage()
        {
            var answer = new QuizQuestionAnswer { Answer = "Test Answer" };
            visualizer.DrawAnswerStatus(true, answer);
            string expectedOutput = "Your answer is correct. Continue with \"enter\".\r\n";
            Assert.AreEqual(expectedOutput, this.stringWriter.ToString());
        }

        [Test]
        public void DrawAnswerStatus_IncorrectAnswer_ShouldDisplayIncorrectMessage()
        {
            var answer = new QuizQuestionAnswer { Answer = "Test Answer" };
            visualizer.DrawAnswerStatus(false, answer);
            string expectedOutput = string.Format("Your answer isn't correct. The correct answer is: \"{0}\". Continue with \"enter\".\r\n", answer.Answer);
            Assert.AreEqual(expectedOutput, this.stringWriter.ToString());
        }

        [TearDown]
        public void TearDown()
        {
            this.stringWriter.Close();
        }
    }
}
