// ********RoostGPT********
// Test generated by RoostGPT for test csharp-testing using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using System.IO;
using LunarDoggo.QuizGame.Visuals;
using NUnit.Framework;


namespace LunarDoggo.QuizGame.Visuals.Test
{
    [TestFixture]
    public class DrawAnswerStatus_27e98f06a4
    {
        private StringWriter stringWriter;
        private ConsoleVisualizer consoleVisualizer;

        [SetUp]
        public void Setup()
        {
            stringWriter = new StringWriter();
            Console.SetOut(stringWriter);
            consoleVisualizer = new ConsoleVisualizer();
        }

        [Test]
        public void DrawAnswerStatus_CorrectAnswer_ShouldDisplayCorrectMessage()
        {
            var correctAnswer = new QuizQuestionAnswer 
            { 
                Answer = "Correct Answer",
                Id = Guid.NewGuid()
            };

            consoleVisualizer.DrawAnswerStatus(true, correctAnswer);

            var output = stringWriter.ToString().Trim();
            Assert.AreEqual("Your answer is correct. Continue with \"enter\".", output);
        }

        [Test]
        public void DrawAnswerStatus_WrongAnswer_ShouldDisplayCorrectMessage()
        {
            var correctAnswer = new QuizQuestionAnswer 
            { 
                Answer = "Correct Answer",
                Id = Guid.NewGuid()
            };

            consoleVisualizer.DrawAnswerStatus(false, correctAnswer);

            var output = stringWriter.ToString().Trim();
            Assert.AreEqual($"Your answer isn't correct. The correct answer is: \"{correctAnswer.Answer}\". Continue with \"enter\".", output);
        }

        [TearDown]
        public void Teardown()
        {
            stringWriter.Close();
        }
    }
}
